/**
 * Official team & production data for Fazenda Pantaneiros - West Fox
 * Real leadership: Raquel Souza, Vaticano, William Erick, Abraão
 */

export const INITIAL_MEMBERS = [
  {
    id: 'mem-master',
    name: 'Master',
    role: 'master',
    roleLabel: 'Administrador Master Holding',
    companyId: 'all',
    avatar: '⚡',
    passport: '00',
    phone: '',
    pin: '9999',
    active: true,
  },
  {
    id: 'mem-raquel',
    name: 'Raquel Souza',
    role: 'owner',
    roleLabel: 'Dona da Fazenda',
    companyId: 'comp-fazenda',
    avatar: '👑',
    passport: '70',
    phone: '',
    pin: '1234',
    active: true,
  },
  {
    id: 'mem-vaticano',
    name: 'Vaticano',
    role: 'owner',
    roleLabel: 'Dono da Fazenda',
    companyId: 'comp-fazenda',
    avatar: '👑',
    passport: '',
    phone: '',
    pin: '1234',
    active: true,
  },
  {
    id: 'mem-william',
    name: 'William Erick',
    role: 'manager',
    roleLabel: 'Gerente Geral',
    companyId: 'comp-fazenda',
    avatar: '⭐',
    passport: '69',
    phone: '',
    pin: '1234',
    active: true,
  },
  {
    id: 'mem-abraao',
    name: 'Abraão',
    role: 'manager',
    roleLabel: 'Gerente de Operações',
    companyId: 'comp-fazenda',
    avatar: '👔',
    passport: '',
    phone: '',
    pin: '1234',
    active: true,
  },
];

export const INITIAL_COMPANIES = [
  {
    id: 'comp-fazenda',
    name: 'Fazenda Pantaneiros',
    type: 'farm',
    code: 'WEST FOX • 82',
    segment: 'Agricultura & Grãos',
    icon: '🌾',
    unitLabel: 'Sacas de Milho',
    themeColor: 'amber',
    description: 'Produção agrícola de milho, sementes e insumos em West Fox.',
    createdAt: '2026-09-15T00:00:00.000Z',
  },
  {
    id: 'comp-ferrovia',
    name: 'Ferrovia West Fox',
    type: 'railroad',
    code: 'RAIL • 01',
    segment: 'Logística & Transporte Ferroviário',
    icon: '🚂',
    unitLabel: 'Cargas de Carvão',
    themeColor: 'slate',
    description: 'Transporte de cargas pesadas, carvão, minérios e passageiros na ferrovia regional.',
    createdAt: '2026-09-18T00:00:00.000Z',
  },
  {
    id: 'comp-taverna',
    name: 'Taverna dos Pantaneiros',
    type: 'tavern',
    code: 'TAV • 82',
    segment: 'Taberna, Comidas & Bebidas',
    icon: '🍺',
    unitLabel: 'Barris de Bebida',
    themeColor: 'orange',
    description: 'Ponto de encontro, bar e fornecimento de refeições e bebidas aos colonos e viajantes.',
    createdAt: '2026-09-20T00:00:00.000Z',
  },
];

// Faturamento Total Inicial Fazenda: $ 26.500,00 | Saldo Atual no Caixa: $ 14.344,03 DOLS
export const INITIAL_TRANSACTIONS = [
  {
    id: 'tx-pantanal-02',
    companyId: 'comp-fazenda',
    type: 'expense',
    amount: 12155.97,
    memberId: 'mem-william',
    memberName: 'William Erick [69]',
    category: 'Folha de Pagamento',
    description: 'Saques parciais de pagamento da equipe no baú da fazenda',
    date: new Date().toISOString(),
    boxBalanceAfter: 14344.03,
  },
  {
    id: 'tx-pantanal-01',
    companyId: 'comp-fazenda',
    type: 'income',
    amount: 26500,
    memberId: 'mem-raquel',
    memberName: 'Raquel Souza [70]',
    category: 'Produção da Fazenda',
    description: 'Faturamento Total da Produção do Turno',
    date: '2026-09-19T18:00:00.000Z',
    boxBalanceAfter: 26500,
  },
  // Ferrovia initial fund
  {
    id: 'tx-ferrovia-01',
    companyId: 'comp-ferrovia',
    type: 'income',
    amount: 18000,
    memberId: 'mem-raquel',
    memberName: 'Raquel Souza [70]',
    category: 'Transporte de Cargas',
    description: 'Faturamento de frete e transporte de carvão no trem cargueiro',
    date: new Date().toISOString(),
    boxBalanceAfter: 18000,
  },
  // Taverna initial fund
  {
    id: 'tx-taverna-01',
    companyId: 'comp-taverna',
    type: 'income',
    amount: 9500,
    memberId: 'mem-raquel',
    memberName: 'Raquel Souza [70]',
    category: 'Venda de Bebidas & Refeições',
    description: 'Caixa arrecadado no balcão da Taverna dos Pantaneiros',
    date: new Date().toISOString(),
    boxBalanceAfter: 9500,
  },
];

export const INITIAL_GOALS = [
  {
    id: 'goal-milho-1',
    companyId: 'comp-fazenda',
    title: 'Meta de 100 Sacas de Milho - Turno Oficial',
    type: 'owner_to_manager',
    unitType: 'sacks',
    unitLabel: 'Sacas de Milho',
    creatorRole: 'owner',
    creatorName: 'Raquel Souza',
    targetMemberId: 'mem-william',
    targetMemberName: 'William Erick [69]',
    targetAmount: 100,
    currentAmount: 0,
    deadline: '2026-09-30',
    status: 'in_progress',
    notes: 'Entregar para os gerentes William Erick ou Abraão no silo central.',
  },
  {
    id: 'goal-ferrovia-1',
    companyId: 'comp-ferrovia',
    title: 'Meta de 50 Cargas de Carvão na Estação',
    type: 'owner_to_manager',
    unitType: 'sacks',
    unitLabel: 'Cargas de Carvão',
    creatorRole: 'owner',
    creatorName: 'Raquel Souza',
    targetMemberId: 'all',
    targetMemberName: 'Toda a Equipe (Geral)',
    targetAmount: 50,
    currentAmount: 12,
    deadline: '2026-10-05',
    status: 'in_progress',
    notes: 'Descarregar no pátio ferroviário de West Fox.',
  },
  {
    id: 'goal-taverna-1',
    companyId: 'comp-taverna',
    title: 'Meta de 80 Barris de Bebida para o Final de Semana',
    type: 'owner_to_manager',
    unitType: 'sacks',
    unitLabel: 'Barris de Bebida',
    creatorRole: 'owner',
    creatorName: 'Raquel Souza',
    targetMemberId: 'all',
    targetMemberName: 'Toda a Equipe (Geral)',
    targetAmount: 80,
    currentAmount: 25,
    deadline: '2026-10-02',
    status: 'in_progress',
    notes: 'Armazenar na adega dos fundos da Taverna.',
  },
];

export const INITIAL_DELIVERIES = [];

// Split Oficial: 30% Caixa da Fazenda ($ 7.950,00) | 70% Folha de Pagamentos ($ 18.550,00)
export const INITIAL_SPLIT_SETTINGS = {
  farmReservePercent: 30, // 30% para sementes, insumos e manutenção
  managersPercent: 35,    // Base e Bônus dos Gerentes
  membersPercent: 35,     // Base dos Donos e Produtores
  bonusForGoalAchieved: 883.33,
};

// Rotas & Missões com Checklist (Fazenda, Ferrovia, Taverna)
export const INITIAL_ROUTES = [
  {
    id: 'route-fazendeiros-01',
    companyId: 'comp-fazenda',
    title: 'Entrega de Fazendeiros',
    rewardAmount: 2300,
    icon: '📦',
    description: 'Coleta e entrega de sacas agrícolas da fazenda para o entreposto comercial.',
    status: 'in_progress',
    startedBy: 'William Erick',
    startedAt: new Date().toISOString(),
    completedAt: null,
    items: [
      { id: 'item-cafe', name: 'Saco de café', targetAmount: 15, currentAmount: 0, completed: false, unit: 'sacos' },
      { id: 'item-amora', name: 'Saco de Amora', targetAmount: 15, currentAmount: 0, completed: false, unit: 'sacos' },
      { id: 'item-algodao', name: 'Saco de algodão', targetAmount: 15, currentAmount: 0, completed: false, unit: 'sacos' },
      { id: 'item-milho', name: 'Saco de Milho', targetAmount: 15, currentAmount: 0, completed: false, unit: 'sacos' },
      { id: 'item-maca', name: 'Saco de Maçã', targetAmount: 15, currentAmount: 0, completed: false, unit: 'sacos' },
      { id: 'item-banana', name: 'Saco de Banana', targetAmount: 15, currentAmount: 0, completed: false, unit: 'sacos' },
    ],
  },
  {
    id: 'route-animal-01',
    companyId: 'comp-ferrovia',
    title: 'Rota de Animais',
    rewardAmount: 4600,
    icon: '🐄',
    description: 'Gestão de Estoque & Produção: 1 rota = 20x queijos/manteiga e 100x leites/ovos/chá. Meta total = 20 rotas ($ 4.600/rota).',
    status: 'in_progress',
    startedBy: 'William Erick',
    startedAt: new Date().toISOString(),
    completedAt: null,
    items: [
      { id: 'item-manteiga', name: 'Manteiga', icon: '🧈', perRoute: 20, targetAmount: 400, currentAmount: 400, completed: true, unit: 'un' },
      { id: 'item-requeijao', name: 'Requeijão', icon: '🥣', perRoute: 20, targetAmount: 400, currentAmount: 400, completed: true, unit: 'un' },
      { id: 'item-coalhada', name: 'Coalhada', icon: '🥛', perRoute: 20, targetAmount: 400, currentAmount: 400, completed: true, unit: 'un' },
      { id: 'item-queijao', name: 'Queijão', icon: '🧀', perRoute: 20, targetAmount: 400, currentAmount: 400, completed: true, unit: 'un' },
      { id: 'item-queijo-cabra', name: 'Queijo de Cabra', icon: '🐐', perRoute: 20, targetAmount: 400, currentAmount: 400, completed: true, unit: 'un' },
      { id: 'item-leite-vaca', name: 'Leite de Vaca', icon: '🥛', perRoute: 100, targetAmount: 2000, currentAmount: 2000, completed: true, unit: 'un' },
      { id: 'item-ovos', name: 'Ovos', icon: '🥚', perRoute: 100, targetAmount: 2000, currentAmount: 2000, completed: true, unit: 'un' },
      { id: 'item-leite-cabra', name: 'Leite de Cabra', icon: '🥛', perRoute: 100, targetAmount: 2000, currentAmount: 2000, completed: true, unit: 'un' },
      { id: 'item-cha', name: 'Chá', icon: '🍵', perRoute: 100, targetAmount: 2000, currentAmount: 2000, completed: true, unit: 'un' },
    ],
  },
  {
    id: 'route-ferrovia-01',
    companyId: 'comp-ferrovia',
    title: 'Rota Ferroviária Expressa West Fox',
    rewardAmount: 4200,
    icon: '🚂',
    description: 'Carga pesada da ferrovia: transporte de laticínios, minérios e carvão.',
    status: 'in_progress',
    startedBy: 'William Erick',
    startedAt: new Date().toISOString(),
    completedAt: null,
    items: [
      { id: 'item-leite', name: 'Garrafas de Leite', targetAmount: 400, currentAmount: 0, completed: false, unit: 'garrafas' },
      { id: 'item-carvao', name: 'Cargas de Carvão', targetAmount: 50, currentAmount: 0, completed: false, unit: 'cargas' },
      { id: 'item-ferro', name: 'Barras de Ferro', targetAmount: 80, currentAmount: 0, completed: false, unit: 'barras' },
      { id: 'item-madeira', name: 'Toras de Madeira', targetAmount: 120, currentAmount: 0, completed: false, unit: 'toras' },
    ],
  },
  {
    id: 'route-taverna-01',
    companyId: 'comp-taverna',
    title: 'Abastecimento da Taberna dos Pantaneiros',
    rewardAmount: 3100,
    icon: '🍺',
    description: 'Reposição de barris de chopp, whisky artesanal e carnes nobres.',
    status: 'template',
    startedBy: null,
    startedAt: null,
    completedAt: null,
    items: [
      { id: 'item-cerveja', name: 'Barris de Cerveja', targetAmount: 30, currentAmount: 0, completed: false, unit: 'barris' },
      { id: 'item-whisky', name: 'Barris de Whisky', targetAmount: 20, currentAmount: 0, completed: false, unit: 'barris' },
      { id: 'item-carne', name: 'Carnes de Caça', targetAmount: 50, currentAmount: 0, completed: false, unit: 'cortes' },
      { id: 'item-trigo', name: 'Sacos de Trigo', targetAmount: 40, currentAmount: 0, completed: false, unit: 'sacos' },
    ],
  },
];
